# Generated by Django 5.0 on 2024-03-11 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
                ('travellers', models.ManyToManyField(related_name='travelled_trips', to=settings.AUTH_USER_MODEL)),
                ('viewers', models.ManyToManyField(related_name='viewed_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
