# Generated by Django 5.0 on 2024-03-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
