# Generated by Django 5.0 on 2024-03-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='image',
            field=models.ImageField(default='default_trip.png', upload_to='trip_pics'),
        ),
    ]
