# Generated by Django 5.0 on 2024-03-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='trip_id',
            new_name='trip',
        ),
    ]
