# Generated by Django 5.0 on 2024-03-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_rename_trip_id_post_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='travel.trip'),
        ),
    ]
