# Generated by Django 5.0 on 2024-03-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
