# Generated by Django 5.0 on 2024-03-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_post_latitude_post_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, upload_to='trip_pics'),
        ),
    ]
